version: '3.4'
services:
    tokengenerator_docker:
        image: node:alpine
        container_name: WhatIsMyIP
        command: /bin/sh -c "cd /srv/app && npm install && node index.js"
        working_dir: /srv/app
        network_mode: host
        restart: never
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
